**MENTR analysis on the ICM cluster - pull outputs**    
B Rioux
22 April 2026

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

# ── Set up figure ──────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(15, 6.5),
                         gridspec_kw={'width_ratios': [1.1, 1]})
fig.suptitle('Balanced (Horizontal) Pleiotropy', fontsize=16, fontweight='bold', y=1.01)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Panel A – MR Scatter Plot with Balanced Pleiotropy
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ax = axes[0]
np.random.seed(42)

n_snps = 25
true_causal = 0.50

# SNP–exposure effects (all positive – valid instruments)
beta_x = np.random.uniform(0.04, 0.40, n_snps)

# Balanced pleiotropic effects: mean ≈ 0
pleiotropy = np.random.normal(0, 0.04, n_snps)

# SNP–outcome = causal effect × SNP–exposure + balanced pleiotropy + noise
beta_y = true_causal * beta_x + pleiotropy + np.random.normal(0, 0.015, n_snps)

se_x = np.random.uniform(0.010, 0.030, n_snps)
se_y = np.random.uniform(0.020, 0.045, n_snps)

# Points with error bars
ax.errorbar(beta_x, beta_y, xerr=se_x, yerr=se_y,
            fmt='o', color='#4C72B0', alpha=0.70, markersize=7,
            capsize=2, elinewidth=0.8, label='SNP instruments')

# IVW line (through origin)
x_line = np.linspace(0, 0.45, 200)
ax.plot(x_line, true_causal * x_line, '-',
        color='#C44E52', lw=2.2, label=f'IVW  (β = {true_causal:.2f})')

# MR-Egger line (with intercept — should be ≈ 0 under balanced pleiotropy)
egger_coefs = np.polyfit(beta_x, beta_y, 1)        # [slope, intercept]
ax.plot(x_line, np.polyval(egger_coefs, x_line), '--',
        color='#55A868', lw=2.2,
        label=f'MR-Egger  (int = {egger_coefs[1]:+.3f})')

ax.axhline(0, color='grey', ls=':', lw=0.7, alpha=0.6)
ax.axvline(0, color='grey', ls=':', lw=0.7, alpha=0.6)
ax.set_xlabel('SNP – Exposure association  ($\\hat\\beta_{Xj}$)', fontsize=11)
ax.set_ylabel('SNP – Outcome association  ($\\hat\\beta_{Yj}$)', fontsize=11)
ax.set_title('A.  MR scatter plot', fontsize=13, fontweight='bold', loc='left')
ax.legend(fontsize=9, framealpha=0.9)

# Annotation
ax.annotate('Pleiotropic effects scatter\nsymmetrically around the\ncausal-estimate line\n→ intercept ≈ 0',
            xy=(0.30, true_causal*0.30 + 0.04), fontsize=8.5,
            xytext=(0.08, 0.20),
            arrowprops=dict(arrowstyle='->', color='#555555', lw=1.2),
            bbox=dict(boxstyle='round,pad=0.35', fc='#FFFDE7', ec='#CCCCCC'),
            color='#333333')

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Panel B – Conceptual DAG
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ax2 = axes[1]
ax2.set_xlim(-0.5, 10.5)
ax2.set_ylim(-0.5, 10.5)
ax2.axis('off')
ax2.set_title('B.  Conceptual diagram', fontsize=13, fontweight='bold', loc='left')

# ── helper: draw a rounded box ────────────────────────────────
def draw_box(ax, xy, text, color='#E3F2FD', ec='#1565C0', fontsize=11):
    w, h = 2.2, 1.0
    box = FancyBboxPatch((xy[0] - w/2, xy[1] - h/2), w, h,
                         boxstyle="round,pad=0.15", fc=color, ec=ec, lw=1.6)
    ax.add_patch(box)
    ax.text(xy[0], xy[1], text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold', color=ec)

# ── nodes ─────────────────────────────────────────────────────
draw_box(ax2, (1.5, 5), 'G\n(SNP)', color='#FFF9C4', ec='#F57F17')
draw_box(ax2, (5, 8.5), 'Exposure\n(X)', color='#E3F2FD', ec='#1565C0')
draw_box(ax2, (9, 5), 'Outcome\n(Y)', color='#FFEBEE', ec='#C62828')
draw_box(ax2, (5, 5), 'Pathway 1', color='#E8F5E9', ec='#2E7D32', fontsize=9.5)
draw_box(ax2, (5, 1.5), 'Pathway 2', color='#F3E5F5', ec='#6A1B9A', fontsize=9.5)

# ── arrows ────────────────────────────────────────────────────
arrow_kw = dict(arrowstyle='->', lw=2, mutation_scale=18)

# G → X  (causal pathway — thick)
ax2.annotate('', xy=(3.8, 8.5), xytext=(2.7, 5.6),
             arrowprops=dict(**arrow_kw, color='#1565C0'))
ax2.text(2.6, 7.4, '$\\beta_{GX}$', fontsize=10, color='#1565C0', fontweight='bold')

# X → Y  (causal effect)
ax2.annotate('', xy=(7.8, 5.7), xytext=(6.2, 8.2),
             arrowprops=dict(**arrow_kw, color='#C62828'))
ax2.text(7.4, 7.4, '$\\beta_{XY}$', fontsize=10, color='#C62828', fontweight='bold')

# G → Pathway 1 (positive pleiotropy)
ax2.annotate('', xy=(3.8, 5), xytext=(2.7, 5),
             arrowprops=dict(**arrow_kw, color='#2E7D32'))

# Pathway 1 → Y  (+δ)
ax2.annotate('', xy=(7.8, 5.2), xytext=(6.2, 5.1),
             arrowprops=dict(**arrow_kw, color='#2E7D32'))
ax2.text(6.8, 5.55, '$+\\delta_1$', fontsize=10, color='#2E7D32', fontweight='bold')

# G → Pathway 2 (negative pleiotropy)
ax2.annotate('', xy=(3.8, 1.5), xytext=(2.7, 4.4),
             arrowprops=dict(**arrow_kw, color='#6A1B9A'))

# Pathway 2 → Y  (−δ)
ax2.annotate('', xy=(7.8, 4.5), xytext=(6.2, 2.0),
             arrowprops=dict(**arrow_kw, color='#6A1B9A'))
ax2.text(6.8, 2.8, '$-\\delta_2$', fontsize=10, color='#6A1B9A', fontweight='bold')

# ── balance annotation ────────────────────────────────────────
ax2.text(5, -0.2,
         'Balanced pleiotropy:  $\\mathbb{E}[\\delta] = 0$\n'
         '($+\\delta_1$ and $-\\delta_2$ cancel on average)',
         ha='center', va='top', fontsize=10,
         bbox=dict(boxstyle='round,pad=0.4', fc='#FFFDE7', ec='#BDBDBD'),
         color='#333333')

plt.tight_layout()
plt.savefig('balanced_pleiotropy.png', dpi=200, bbox_inches='tight', facecolor='white')
plt.show()

:

Select R Kernel in Jupyter kernels -> R (r_env)

In [ ]:
library(dplyr)
library(data.table)
library(R.utils)
library(openxlsx)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

# Load ontology mapping

In [ ]:
# Load ontology file (sample_ontology_ID -> cell type term)
ontology <- fread("/network/iss/debette/users/bastien.rioux/mentr/MENTR/resources/supp_table_10.sample_ontology_information.tsv.gz")

# Check it
head(ontology[, .(sample_ontology_ID, sample_ontology_term, sample_ontology_type)])

# Load CAGE cluster info (clusterID -> gene name, type, etc.)
cage_info <- fread("/network/iss/debette/users/bastien.rioux/mentr/MENTR/resources/F5.cage_cluster.hg19.info.tsv.gz")

# Check it
head(cage_info[, .(clusterID, clusterName, type, geneNameStr, geneClassStr)])

  sample_ontology_ID sample_ontology_term      sample_ontology_type
1 CL:0000034         stem cell                 cell_type
2 CL:0000037         hematopoietic stem cell   cell_type
3 CL:0000047         neuronal stem cell        cell_type
4 CL:0000049         common myeloid progenitor cell_type
5 CL:0000056         myoblast                  cell_type
6 CL:0000057         fibroblast                cell_type

  clusterID                    clusterName          type     geneNameStr
1 chr10:100013403..100013414,- p2@LOXL4             promoter LOXL4
2 chr10:100019738-100019959    e1@ADDG10100019738.E enhancer ADDG10100019738.E
3 chr10:100020230-100020246    e1@ADDG10100020230.E enhancer ADDG10100020230.E
4 chr10:100027943..100027958,- p1@LOXL4             promoter LOXL4
5 chr10:100074404-100074582    e1@ADDG10100074404.E enhancer ADDG10100074404.E
6 chr10:100076038-100076149    e1@ADDG10100076038.E enhancer ADDG10100076038.E
  geneClassStr
1 coding_mRNA
2 enhancer_locus
3 enhancer_locus
4 coding_mRNA
5 enhancer_locus
6 enhancer_locus

# (Explore test run)

Read the output file named all_qcd_res.txt.gz located in the directory /network/iss/debette/users/bastien.rioux/mentr/output_test/output/ using the read.csv function in R. The file is tab-separated and contains a header row.

In [ ]:
all_qcd_res <- fread("/network/iss/debette/users/bastien.rioux/mentr/output_test/output/all_qcd_res.txt.gz")

In [ ]:
str(all_qcd_res)

Classes ‘data.table’ and 'data.frame':	235 obs. of  356 variables:
 $ CHR           : chr  "chr1" "chr1" "chr1" "chr1" ...
 $ POS           : int  1999288 2001856 2004947 2008444 2001273 1999288 2001856 2004947 2008444 2001273 ...
 $ REF           : chr  "T" "A" "T" "T" ...
 $ ALT           : chr  "C" "G" "C" "C" ...
 $ dist          : int  89045 91613 94704 98201 91030 84577 87145 90236 93733 86562 ...
 $ gene          : chr  "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" ...
 $ strand        : chr  "+" "+" "+" "+" ...
 $ ref_matched   : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ CL:0000034    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000037    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000047    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000049    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000056    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000057    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000062    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000066    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000067    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000071    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000076    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000077    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000082    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000084    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000094    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000097    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000115    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000127    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000133    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000134    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000136    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000138    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000147    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000148    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000151    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000153    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000154    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000182    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000187    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000188    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000192    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000213    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000214    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000221    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000222    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000223    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000234    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000235    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000236    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000307    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000312    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000327    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000346    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000359    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000362    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000388    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000451    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000453    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000499    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000513    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000515    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000540    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000542    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000558    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000569    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000575    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000576    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000594    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000622    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000623    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000624    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000625    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000630    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000632    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000669    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000708    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000710    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000731    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000737    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000738    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000763    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000766    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000767    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000771    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000775    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000784    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000789    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000798    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000837    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000840    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000842    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000860    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000893    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000988    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000990    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0001014    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002076    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002077    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002078    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002092    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002138    : num  0 0 0 0 0 0 0 0 0 0 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

In [ ]:
# Keep only reliable records
dim(all_qcd_res)
all_res_qced <- all_qcd_res[ref_matched == TRUE]
dim(all_res_qced)

[1] 235 356

[1] 235 356

> Read .csv file (hg19) containing rsid and chr/pos/ea/nea (needs to be downloaded directly from DNA Nexus with wget in mentr/input/)

DNA nexus path: /shivai_analyses/gwas/postgwas/mentr/input/

In CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/
- wget https://dl.ew2.dnanex.us/F/D/J20j9J68bJ4XPXG2x9vfXB1VfP9JXyv3YfXJjYv8/mentr_input_hg19.csv

In [ ]:
rsid_table <- fread("/network/iss/debette/users/bastien.rioux/mentr/input/mentr_input_hg19.csv")
head(rsid_table)

  rsid       chr pos     ea nea
1 rs2459985  1   1999288 C  T
2 rs2803303  1   2001856 G  A
3 rs2678942  1   2004947 C  T
4 rs13302948 1   2008444 C  T
5 rs2678941  1   2001273 G  A
6 rs2254669  1   2006108 G  A

> CS file to map rsID

DNA nexus path: /shivai_analyses/gwas/postgwas/susie_r/

in CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/ 
- wget https://dl.ew2.dnanex.us/F/D/JZvVvjQqj309jZjzFKzKK7YY4y4kby69Y21fz81X/susierss_cs_snps_20260417.xlsx

In [ ]:
cs_table <- read.xlsx("/network/iss/debette/users/bastien.rioux/mentr/input/susierss_cs_snps_20260417.xlsx")
# Add susierss prefix
rsid_col <- "rsID"   # ← change if column is named differently e.g. "rsid"
colnames(cs_table) <- ifelse(
  colnames(cs_table) == rsid_col,
  colnames(cs_table),                            # keep rsID as-is
  paste0("susierss_", colnames(cs_table))        # prefix all others
)
cat("\ncs_table columns after prefix:\n")
print(colnames(cs_table))

cs_table columns after prefix:
 [1] "susierss_trait"              "susierss_risk_loci_num"
 [3] "susierss_cs"                 "rsID"
 [5] "susierss_pip"                "susierss_pip_rank"
 [7] "susierss_locus_gene"         "susierss_locus_start"
 [9] "susierss_locus_end"          "susierss_locus_cytoband"
[11] "susierss_CHR"                "susierss_POS"
[13] "susierss_EA"                 "susierss_NEA"
[15] "susierss_EAF"                "susierss_BETA"
[17] "susierss_SE"                 "susierss_P"
[19] "susierss_INFO"               "susierss_is_indep_snp"
[21] "susierss_indep_snp_method"   "susierss_snp_gene"
[23] "susierss_snp_func"           "susierss_NOVEL"
[25] "susierss_b2_replicated"      "susierss_b2_replicated_bonf"

> Format output

In [ ]:
library(data.table)

# ── Harmonize CHR format ──────────────────────────────────────────────────────
rsid_table[, chr := paste0("chr", chr)]

cat("df_long CHR examples:    ", head(df_long$CHR), "\n")
cat("rsid_table chr examples: ", head(rsid_table$chr), "\n")

# ── Fixed columns (metadata) ──────────────────────────────────────────────────
meta_cols <- c("CHR", "POS", "REF", "ALT", "dist", "gene", "strand", "ref_matched")

# ── Cell type columns ─────────────────────────────────────────────────────────
cell_cols <- setdiff(colnames(all_res_qced), meta_cols)

# ── Melt to long format ───────────────────────────────────────────────────────
df_long <- melt(all_res_qced,
                id.vars       = meta_cols,
                variable.name = "cell_type",
                value.name    = "delta_prob")

# ── Join rsID ─────────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  rsid_table[, .(rsid, chr, pos, ea, nea)],
  by.x  = c("CHR", "POS", "ALT", "REF"),
  by.y  = c("chr", "pos", "ea",  "nea"),
  all.x = TRUE
)

n_total   <- nrow(df_long)
n_matched <- df_long[!is.na(rsid), .N]
cat("Variants with rsID   :", n_matched, "\n")
cat("Variants without rsID:", n_total - n_matched, "\n")

# ── Join ontology ─────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  ontology[, .(sample_ontology_ID,
               sample_ontology_term,
               sample_ontology_type)],
  by.x  = "cell_type",
  by.y  = "sample_ontology_ID",
  all.x = TRUE
)

# ── Join CAGE info ────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  cage_info[, .(clusterID,
                clusterName,
                type,
                geneNameStr,
                geneClassStr)],
  by.x  = "gene",
  by.y  = "clusterID",
  all.x = TRUE
)

# ── Join SuSiE RSS CS table by rsid ──────────────────────────────────────────
df_long <- merge(
  df_long,
  cs_table,             # all susierss_ prefixed cols + rsID
  by.x  = "rsid",
  by.y  = "rsID",       # ← original rsID col name before prefix
  all.x = TRUE          # keep all df_long rows
)

# Check match rate
n_in_cs <- df_long[!is.na(susierss_cs), .N]   # ← replace susierss_cs with any known col
cat("Variants matched to SuSiE CS table:", n_in_cs, "\n")

# ── Reorder columns ───────────────────────────────────────────────────────────
# Get all susierss_ columns dynamically
susierss_cols <- grep("^susierss_", colnames(df_long), value = TRUE)

col_order <- c("gene", "clusterName", "type", "geneNameStr", "geneClassStr",
               "cell_type", "sample_ontology_term", "sample_ontology_type",
               "rsid", "CHR", "POS", "REF", "ALT", "dist", "strand", "delta_prob",
               susierss_cols)   # ← appended at the end

df_long <- df_long[, ..col_order]

# Preview
head(df_long)
cat("\nFinal columns:\n")
print(colnames(df_long))

# ── Filter effects ────────────────────────────────────────────────────────────
robust <- df_long[abs(delta_prob) >= 0.1]
cat("Robust effects     (|Δprob| >= 0.1) :", nrow(robust), "\n")

permissive <- df_long[abs(delta_prob) >= 0.05]
cat("Permissive effects (|Δprob| >= 0.05):", nrow(permissive), "\n")

ERROR: Error: object 'df_long' not found

In [ ]:
head(permissive)

  gene                    clusterName type     geneNameStr geneClassStr cell_type      sample_ontology_term  sample_ontology_type rsid       CHR  ⋯ susierss_SE susierss_P  susierss_INFO susierss_is_indep_snp susierss_indep_snp_method susierss_snp_gene susierss_snp_func susierss_NOVEL susierss_b2_replicated susierss_b2_replicated_bonf
1 chr1:2005462..2005537,+ p7@PRKCZ    promoter PRKCZ       coding_mRNA  UBERON:0000353 parenchyma            tissue               rs13302948 chr1 ⋯ 0.006090    4.17714e-08 0.997427      FALSE                 NA                        NA                NA
2 chr1:2005046..2005122,+ p1@PRKCZ    promoter PRKCZ       coding_mRNA  UBERON:0001896 medulla oblongata     tissue               rs2678942  chr1 ⋯ 0.006023    2.80590e-08 0.996439      FALSE                 NA                        NA                NA
3 chr1:2005046..2005122,+ p1@PRKCZ    promoter PRKCZ       coding_mRNA  UBERON:0004875 nephrogenic cord      tissue               rs2678942  chr1 ⋯ 0.006023    2.80590e-08 0.996439      FALSE                 NA                        NA                NA
4 chr1:2005126..2005153,+ p5@PRKCZ    promoter PRKCZ       coding_mRNA  UBERON:0004151 cardiac chamber       tissue               rs2678942  chr1 ⋯ 0.006023    2.80590e-08 0.996439      FALSE                 NA                        NA                NA
5 chr1:2005182..2005194,+ p8@PRKCZ    promoter PRKCZ       coding_mRNA  UBERON:0003513 trunk blood vessel    tissue               rs2678942  chr1 ⋯ 0.006023    2.80590e-08 0.996439      FALSE                 NA                        NA                NA
6 chr1:2005228..2005248,+ p3@PRKCZ    promoter PRKCZ       coding_mRNA  CL:0000134     mesenchymal stem cell cell_type            rs2678942  chr1 ⋯ 0.006023    2.80590e-08 0.996439      FALSE                 NA                        NA                NA

In [ ]:
write.xlsx(permissive, 
           "/network/iss/debette/users/bastien.rioux/mentr/output_test/permissive_test.xlsx")

# (Explore parallel test run)

Read the output file named all_qcd_res.txt.gz located in the directory /network/iss/debette/users/bastien.rioux/mentr/output_test/output/ using the read.csv function in R. The file is tab-separated and contains a header row.

In [ ]:
all_qcd_res <- fread("/network/iss/debette/users/bastien.rioux/mentr/output_test_parallel/output/all_qcd_res.txt.gz")

In [ ]:
str(all_qcd_res)

Classes ‘data.table’ and 'data.frame':	235 obs. of  356 variables:
 $ CHR           : chr  "chr1" "chr1" "chr1" "chr1" ...
 $ POS           : int  1999288 2001856 2004947 2008444 2001273 1999288 2001856 2004947 2008444 2001273 ...
 $ REF           : chr  "T" "A" "T" "T" ...
 $ ALT           : chr  "C" "G" "C" "C" ...
 $ dist          : int  89045 91613 94704 98201 91030 84577 87145 90236 93733 86562 ...
 $ gene          : chr  "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" "chr1:1910241..1910262,+" ...
 $ strand        : chr  "+" "+" "+" "+" ...
 $ ref_matched   : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ CL:0000034    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000037    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000047    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000049    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000056    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000057    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000062    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000066    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000067    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000071    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000076    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000077    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000082    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000084    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000094    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000097    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000115    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000127    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000133    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000134    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000136    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000138    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000147    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000148    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000151    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000153    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000154    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000182    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000187    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000188    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000192    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000213    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000214    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000221    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000222    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000223    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000234    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000235    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000236    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000307    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000312    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000327    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000346    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000359    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000362    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000388    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000451    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000453    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000499    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000513    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000515    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000540    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000542    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000558    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000569    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000575    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000576    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000594    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000622    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000623    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000624    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000625    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000630    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000632    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000669    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000708    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000710    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000731    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000737    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000738    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000763    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000766    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000767    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000771    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000775    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000784    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000789    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000798    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000837    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000840    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000842    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000860    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000893    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000988    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0000990    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0001014    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002076    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002077    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002078    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002092    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ CL:0002138    : num  0 0 0 0 0 0 0 0 0 0 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

In [ ]:
# Keep only reliable records
dim(all_qcd_res)
all_res_qced <- all_qcd_res[ref_matched == TRUE]
dim(all_res_qced)

[1] 235 356

[1] 235 356

> Read .csv file (hg19) containing rsid and chr/pos/ea/nea (needs to be downloaded directly from DNA Nexus with wget in mentr/input/)

DNA nexus path: /shivai_analyses/gwas/postgwas/mentr/input/

In CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/
- wget https://dl.ew2.dnanex.us/F/D/J20j9J68bJ4XPXG2x9vfXB1VfP9JXyv3YfXJjYv8/mentr_input_hg19.csv

In [ ]:
rsid_table <- fread("/network/iss/debette/users/bastien.rioux/mentr/input/mentr_input_hg19.csv")

# ── Harmonize CHR format ──────────────────────────────────────────────────────
rsid_table[, chr := paste0("chr", chr)]

cat("rsid_table chr examples: ", head(rsid_table$chr), "\n")
head(rsid_table)

rsid_table chr examples:  chr1 chr1 chr1 chr1 chr1 chr1

  rsid       chr  pos     ea nea
1 rs2459985  chr1 1999288 C  T
2 rs2803303  chr1 2001856 G  A
3 rs2678942  chr1 2004947 C  T
4 rs13302948 chr1 2008444 C  T
5 rs2678941  chr1 2001273 G  A
6 rs2254669  chr1 2006108 G  A

> CS file to map rsID

DNA nexus path: /shivai_analyses/gwas/postgwas/susie_r/

in CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/ 
- wget https://dl.ew2.dnanex.us/F/D/JZvVvjQqj309jZjzFKzKK7YY4y4kby69Y21fz81X/susierss_cs_snps_20260417.xlsx

In [ ]:
cs_table <- read.xlsx("/network/iss/debette/users/bastien.rioux/mentr/input/susierss_cs_snps_20260417.xlsx")
# Add susierss prefix
rsid_col <- "rsID"   # ← change if column is named differently e.g. "rsid"
colnames(cs_table) <- ifelse(
  colnames(cs_table) == rsid_col,
  colnames(cs_table),                            # keep rsID as-is
  paste0("susierss_", colnames(cs_table))        # prefix all others
)
cat("\ncs_table columns after prefix:\n")
print(colnames(cs_table))

cs_table columns after prefix:
 [1] "susierss_trait"              "susierss_risk_loci_num"
 [3] "susierss_cs"                 "rsID"
 [5] "susierss_pip"                "susierss_pip_rank"
 [7] "susierss_locus_gene"         "susierss_locus_start"
 [9] "susierss_locus_end"          "susierss_locus_cytoband"
[11] "susierss_CHR"                "susierss_POS"
[13] "susierss_EA"                 "susierss_NEA"
[15] "susierss_EAF"                "susierss_BETA"
[17] "susierss_SE"                 "susierss_P"
[19] "susierss_INFO"               "susierss_is_indep_snp"
[21] "susierss_indep_snp_method"   "susierss_snp_gene"
[23] "susierss_snp_func"           "susierss_NOVEL"
[25] "susierss_b2_replicated"      "susierss_b2_replicated_bonf"

> Format output

In [ ]:
library(data.table)

# ── Fixed columns (metadata) ──────────────────────────────────────────────────
meta_cols <- c("CHR", "POS", "REF", "ALT", "dist", "gene", "strand", "ref_matched")

# ── Cell type columns ─────────────────────────────────────────────────────────
cell_cols <- setdiff(colnames(all_res_qced), meta_cols)

# ── Melt to long format ───────────────────────────────────────────────────────
df_long <- melt(all_res_qced,
                id.vars       = meta_cols,
                variable.name = "cell_type",
                value.name    = "delta_prob")

# ── Join rsID ─────────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  rsid_table[, .(rsid, chr, pos, ea, nea)],
  by.x  = c("CHR", "POS", "ALT", "REF"),
  by.y  = c("chr", "pos", "ea",  "nea"),
  all.x = TRUE
)

n_total   <- nrow(df_long)
n_matched <- df_long[!is.na(rsid), .N]
cat("Variants with rsID   :", n_matched, "\n")
cat("Variants without rsID:", n_total - n_matched, "\n")

# ── Join ontology ─────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  ontology[, .(sample_ontology_ID,
               sample_ontology_term,
               sample_ontology_type)],
  by.x  = "cell_type",
  by.y  = "sample_ontology_ID",
  all.x = TRUE
)

# ── Join CAGE info ────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  cage_info[, .(clusterID,
                clusterName,
                type,
                geneNameStr,
                geneClassStr)],
  by.x  = "gene",
  by.y  = "clusterID",
  all.x = TRUE
)

# ── Join SuSiE RSS CS table by rsid ──────────────────────────────────────────
df_long <- merge(
  df_long,
  cs_table,             # all susierss_ prefixed cols + rsID
  by.x  = "rsid",
  by.y  = "rsID",       # ← original rsID col name before prefix
  all.x = TRUE          # keep all df_long rows
)

# Check match rate
n_in_cs <- df_long[!is.na(susierss_cs), .N]   # ← replace susierss_cs with any known col
cat("Variants matched to SuSiE CS table:", n_in_cs, "\n")

# ── Reorder columns ───────────────────────────────────────────────────────────
# Get all susierss_ columns dynamically
susierss_cols <- grep("^susierss_", colnames(df_long), value = TRUE)

col_order <- c("gene", "clusterName", "type", "geneNameStr", "geneClassStr",
               "cell_type", "sample_ontology_term", "sample_ontology_type",
               "rsid", "CHR", "POS", "REF", "ALT", "dist", "strand", "delta_prob",
               susierss_cols)   # ← appended at the end

df_long <- df_long[, ..col_order]

# Preview
head(df_long)
cat("\nFinal columns:\n")
print(colnames(df_long))

# ── Filter effects ────────────────────────────────────────────────────────────
robust <- df_long[abs(delta_prob) >= 0.1]
cat("Robust effects     (|Δprob| >= 0.1) :", nrow(robust), "\n")

permissive <- df_long[abs(delta_prob) >= 0.05]
cat("Permissive effects (|Δprob| >= 0.05):", nrow(permissive), "\n")

Variants with rsID   : 81780
Variants without rsID: 0
Variants matched to SuSiE CS table: 81780

  gene                    clusterName          type     geneNameStr
1 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
2 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
3 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
4 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
5 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
6 chr1:1910241..1910262,+ p1@CATG00000072713.1 promoter CATG00000072713.1
  geneClassStr     cell_type  sample_ontology_term      sample_ontology_type
1 lncRNA_antisense CL:0000034 stem cell                 cell_type
2 lncRNA_antisense CL:0000037 hematopoietic stem cell   cell_type
3 lncRNA_antisense CL:0000047 neuronal stem cell        cell_type
4 lncRNA_antisense CL:0000049 common myeloid progenitor cell_type
5 lncRNA_antisense CL:0000056 myoblast                  cell_type
6 lncRNA_antisense CL:0000057 fibroblast                cell_type
  rsid       CHR  ⋯ susierss_SE susierss_P  susierss_INFO susierss_is_indep_snp
1 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
2 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
3 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
4 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
5 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
6 rs13302948 chr1 ⋯ 0.00609     4.17714e-08 0.997427      FALSE
  susierss_indep_snp_method susierss_snp_gene susierss_snp_func susierss_NOVEL
1 NA                        NA                NA
2 NA                        NA                NA
3 NA                        NA                NA
4 NA                        NA                NA
5 NA                        NA                NA
6 NA                        NA                NA
  susierss_b2_replicated susierss_b2_replicated_bonf
1
2
3
4
5
6

Final columns:
 [1] "gene"                        "clusterName"
 [3] "type"                        "geneNameStr"
 [5] "geneClassStr"                "cell_type"
 [7] "sample_ontology_term"        "sample_ontology_type"
 [9] "rsid"                        "CHR"
[11] "POS"                         "REF"
[13] "ALT"                         "dist"
[15] "strand"                      "delta_prob"
[17] "susierss_trait"              "susierss_risk_loci_num"
[19] "susierss_cs"                 "susierss_pip"
[21] "susierss_pip_rank"           "susierss_locus_gene"
[23] "susierss_locus_start"        "susierss_locus_end"
[25] "susierss_locus_cytoband"     "susierss_CHR"
[27] "susierss_POS"                "susierss_EA"
[29] "susierss_NEA"                "susierss_EAF"
[31] "susierss_BETA"               "susierss_SE"
[33] "susierss_P"                  "susierss_INFO"
[35] "susierss_is_indep_snp"       "susierss_indep_snp_method"
[37] "susierss_snp_gene"           "susierss_snp_func"
[39] "susierss_NOVEL"              "susierss_b2_replicated"
[41] "susierss_b2_replicated_bonf"
Robust effects     (|Δprob| >= 0.1) : 0
Permissive effects (|Δprob| >= 0.05): 13

In [ ]:
head(permissive)

  gene                    clusterName type     geneNameStr geneClassStr
1 chr1:2005462..2005537,+ p7@PRKCZ    promoter PRKCZ       coding_mRNA
2 chr1:2005046..2005122,+ p1@PRKCZ    promoter PRKCZ       coding_mRNA
3 chr1:2005046..2005122,+ p1@PRKCZ    promoter PRKCZ       coding_mRNA
4 chr1:2005126..2005153,+ p5@PRKCZ    promoter PRKCZ       coding_mRNA
5 chr1:2005182..2005194,+ p8@PRKCZ    promoter PRKCZ       coding_mRNA
6 chr1:2005228..2005248,+ p3@PRKCZ    promoter PRKCZ       coding_mRNA
  cell_type      sample_ontology_term  sample_ontology_type rsid       CHR  ⋯
1 UBERON:0000353 parenchyma            tissue               rs13302948 chr1 ⋯
2 UBERON:0001896 medulla oblongata     tissue               rs2678942  chr1 ⋯
3 UBERON:0004875 nephrogenic cord      tissue               rs2678942  chr1 ⋯
4 UBERON:0004151 cardiac chamber       tissue               rs2678942  chr1 ⋯
5 UBERON:0003513 trunk blood vessel    tissue               rs2678942  chr1 ⋯
6 CL:0000134     mesenchymal stem cell cell_type            rs2678942  chr1 ⋯
  susierss_SE susierss_P  susierss_INFO susierss_is_indep_snp
1 0.006090    4.17714e-08 0.997427      FALSE
2 0.006023    2.80590e-08 0.996439      FALSE
3 0.006023    2.80590e-08 0.996439      FALSE
4 0.006023    2.80590e-08 0.996439      FALSE
5 0.006023    2.80590e-08 0.996439      FALSE
6 0.006023    2.80590e-08 0.996439      FALSE
  susierss_indep_snp_method susierss_snp_gene susierss_snp_func susierss_NOVEL
1 NA                        NA                NA
2 NA                        NA                NA
3 NA                        NA                NA
4 NA                        NA                NA
5 NA                        NA                NA
6 NA                        NA                NA
  susierss_b2_replicated susierss_b2_replicated_bonf
1
2
3
4
5
6

Same results as the quick run

# VCAN

> Read file with hg19 positions and rsID

In [ ]:
rsid_table <- fread("/network/iss/debette/users/bastien.rioux/mentr/input/mentr_input_hg19.csv")
head(rsid_table)

  rsid       chr pos     ea nea
1 rs2459985  1   1999288 C  T
2 rs2803303  1   2001856 G  A
3 rs2678942  1   2004947 C  T
4 rs13302948 1   2008444 C  T
5 rs2678941  1   2001273 G  A
6 rs2254669  1   2006108 G  A

> Read CS

In [ ]:
cs_table <- read.xlsx("/network/iss/debette/users/bastien.rioux/mentr/input/susierss_cs_snps_20260417.xlsx")
cs_table <- cs_table %>% filter(grepl("VCAN", cs_table$locus_gene))
vcan_cs_rsid <- cs_table %>% pull(rsID) %>% unique()
length(vcan_cs_rsid)

[1] 32

> Format input file for VCAN locus

In [ ]:
rsid_table_vcan <- rsid_table %>% filter(rsid %in% vcan_cs_rsid) %>% select(-rsid)
rsid_table_vcan %>% write.table("/network/iss/debette/users/bastien.rioux/mentr/input/vcan_mentr_table.txt", 
                      sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)

# Load and clean chr-level chunk runs

Run section 'Load ontology mapping' first

This is the result from run_mentr_parallel.sh and submit_mentr_chunks.sh.

The script below lead per-chunk results (stored under mentr/output/chunk_*/qcd_res.txt.gz) into a single table with annotations and filtering.

In [ ]:
# Iterate through all_qcd_res files under /network/iss/debette/users/bastien.rioux/mentr/output
library(data.table)

# Define base directory
base_dir <- "/network/iss/debette/users/bastien.rioux/mentr/output"

# Find all all_qcd_res.txt.gz files recursively
files <- list.files(
  path       = base_dir,
  pattern    = "all_qcd_res\\.txt\\.gz$",
  recursive  = TRUE,
  full.names = TRUE
)

# Print files found (sanity check)
cat("Found", length(files), "files:\n")
print(files)

# Read and combine into a single data.table
all_qcd_res <- rbindlist(
  lapply(files, function(f) {
    cat("Reading:", f, "\n")
    fread(f)
  }),
  use.names = TRUE,
  fill      = TRUE   # handles any missing columns across chunks
)

cat("Final dimensions:", nrow(all_qcd_res), "rows x", ncol(all_qcd_res), "cols\n")

Found 8 files:
[1] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_1_chr1-2/output/all_qcd_res.txt.gz"
[2] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_2_chr3-4/output/all_qcd_res.txt.gz"
[3] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_3_chr5-6/output/all_qcd_res.txt.gz"
[4] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_4_chr7-8/output/all_qcd_res.txt.gz"
[5] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_5_chr9-10/output/all_qcd_res.txt.gz"
[6] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_6_chr11-12/output/all_qcd_res.txt.gz"
[7] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_7_chr13-15/output/all_qcd_res.txt.gz"
[8] "/network/iss/debette/users/bastien.rioux/mentr/output/chunk_9_chr19-21/output/all_qcd_res.txt.gz"
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_1_chr1-2/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_2_chr3-4/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_3_chr5-6/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_4_chr7-8/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_5_chr9-10/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_6_chr11-12/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_7_chr13-15/output/all_qcd_res.txt.gz
Reading: /network/iss/debette/users/bastien.rioux/mentr/output/chunk_9_chr19-21/output/all_qcd_res.txt.gz
Final dimensions: 216361 rows x 356 cols

In [ ]:
# Keep only reliable records
dim(all_qcd_res)
all_res_qced <- all_qcd_res[ref_matched == TRUE]
dim(all_res_qced)

[1] 216361    356

[1] 216361    356

In [ ]:
head(all_qcd_res)

  CHR  POS      REF ALT dist  gene                      strand ref_matched
1 chr1 15522936 G   A   44091 chr1:15478839..15478845,- -      TRUE
2 chr1 15558045 C   A   79200 chr1:15478839..15478845,- -      TRUE
3 chr1 15559672 G   A   80827 chr1:15478839..15478845,- -      TRUE
4 chr1 15560025 C   G   81180 chr1:15478839..15478845,- -      TRUE
5 chr1 15558250 A   T   79405 chr1:15478839..15478845,- -      TRUE
6 chr1 15558105 A   T   79260 chr1:15478839..15478845,- -      TRUE
  CL:0000034 CL:0000037 ⋯ UBERON:0009722 UBERON:0009854 UBERON:0010133
1 0          0          ⋯ 0              0              0
2 0          0          ⋯ 0              0              0
3 0          0          ⋯ 0              0              0
4 0          0          ⋯ 0              0              0
5 0          0          ⋯ 0              0              0
6 0          0          ⋯ 0              0              0
  UBERON:0010225 UBERON:0010260 UBERON:0010323 UBERON:0010743 UBERON:0011135
1 0              0              0              0              0
2 0              0              0              0              0
3 0              0              0              0              0
4 0              0              0              0              0
5 0              0              0              0              0
6 0              0              0              0              0
  UBERON:0011137 LCL154
1 0              0
2 0              0
3 0              0
4 0              0
5 0              0
6 0              0

> Read .csv file (hg19) containing rsid and chr/pos/ea/nea (needs to be downloaded directly from DNA Nexus with wget in mentr/input/)

DNA nexus path: /shivai_analyses/gwas/postgwas/mentr/input/

In CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/
- wget https://dl.ew2.dnanex.us/F/D/J20j9J68bJ4XPXG2x9vfXB1VfP9JXyv3YfXJjYv8/mentr_input_hg19.csv

In [ ]:
rsid_table <- fread("/network/iss/debette/users/bastien.rioux/mentr/input/mentr_input_hg19.csv")

# ── Harmonize CHR format ──────────────────────────────────────────────────────
rsid_table[, chr := paste0("chr", chr)]

cat("rsid_table chr examples: ", head(rsid_table$chr), "\n")
head(rsid_table)

rsid_table chr examples:  chr1 chr1 chr1 chr1 chr1 chr1

  rsid       chr  pos     ea nea
1 rs2459985  chr1 1999288 C  T
2 rs2803303  chr1 2001856 G  A
3 rs2678942  chr1 2004947 C  T
4 rs13302948 chr1 2008444 C  T
5 rs2678941  chr1 2001273 G  A
6 rs2254669  chr1 2006108 G  A

> CS file to map rsID

DNA nexus path: /shivai_analyses/gwas/postgwas/susie_r/

in CLI:
- cd /network/iss/debette/users/bastien.rioux/mentr/input/ 
- wget https://dl.ew2.dnanex.us/F/D/JZvVvjQqj309jZjzFKzKK7YY4y4kby69Y21fz81X/susierss_cs_snps_20260417.xlsx

In [ ]:
cs_table <- read.xlsx("/network/iss/debette/users/bastien.rioux/mentr/input/susierss_cs_snps_20260417.xlsx")
# Add susierss prefix
rsid_col <- "rsID"   # ← change if column is named differently e.g. "rsid"
colnames(cs_table) <- ifelse(
  colnames(cs_table) == rsid_col,
  colnames(cs_table),                            # keep rsID as-is
  paste0("susierss_", colnames(cs_table))        # prefix all others
)
cat("\ncs_table columns after prefix:\n")
print(colnames(cs_table))

cs_table columns after prefix:
 [1] "susierss_trait"              "susierss_risk_loci_num"
 [3] "susierss_cs"                 "rsID"
 [5] "susierss_pip"                "susierss_pip_rank"
 [7] "susierss_locus_gene"         "susierss_locus_start"
 [9] "susierss_locus_end"          "susierss_locus_cytoband"
[11] "susierss_CHR"                "susierss_POS"
[13] "susierss_EA"                 "susierss_NEA"
[15] "susierss_EAF"                "susierss_BETA"
[17] "susierss_SE"                 "susierss_P"
[19] "susierss_INFO"               "susierss_is_indep_snp"
[21] "susierss_indep_snp_method"   "susierss_snp_gene"
[23] "susierss_snp_func"           "susierss_NOVEL"
[25] "susierss_b2_replicated"      "susierss_b2_replicated_bonf"

In [ ]:
cs_table

      susierss_trait  susierss_risk_loci_num susierss_cs rsID
1     bianca_deep_wmh 1                      1           rs2459985
2     bianca_deep_wmh 1                      1           rs2803303
3     bianca_deep_wmh 1                      1           rs2678942
4     bianca_deep_wmh 1                      1           rs13302948
5     bianca_deep_wmh 1                      1           rs2678941
6     bianca_deep_wmh 1                      1           rs2254669
7     bianca_deep_wmh 1                      1           rs3121829
8     bianca_deep_wmh 1                      1           rs2490550
9     bianca_deep_wmh 1                      1           rs2490552
10    bianca_deep_wmh 1                      1           rs2490549
11    bianca_deep_wmh 1                      1           rs2459990
12    bianca_deep_wmh 1                      1           rs2459989
13    bianca_deep_wmh 1                      1           rs2803343
14    bianca_deep_wmh 1                      1           rs2803302
15    bianca_deep_wmh 1                      1           rs2803310
16    bianca_deep_wmh 1                      1           rs2803312
17    bianca_deep_wmh 1                      1           rs6684579
18    bianca_deep_wmh 1                      1           rs6693908
19    bianca_deep_wmh 1                      1           rs2459993
20    bianca_deep_wmh 1                      1           rs2490556
21    bianca_deep_wmh 1                      1           rs2249670
22    bianca_deep_wmh 1                      1           rs2459988
23    bianca_deep_wmh 1                      1           rs2678948
24    bianca_deep_wmh 1                      1           rs2459995
25    bianca_deep_wmh 1                      1           rs2678947
26    bianca_deep_wmh 1                      1           rs1108262
27    bianca_deep_wmh 1                      1           rs6694101
28    bianca_deep_wmh 1                      1           rs2490557
29    bianca_deep_wmh 1                      1           rs2803345
30    bianca_deep_wmh 1                      1           rs2678949
⋮     ⋮               ⋮                      ⋮           ⋮
20253 shiva_wmh       64                     1           rs2228619
20254 shiva_wmh       64                     1           rs2073857
20255 shiva_wmh       64                     1           rs9609276
20256 shiva_wmh       64                     1           rs2413043
20257 shiva_wmh       64                     1           rs3208937
20258 shiva_wmh       64                     1           rs4141404
20259 shiva_wmh       64                     1           rs2283879
20260 shiva_wmh       64                     1           rs2413032
20261 shiva_wmh       64                     1           rs9609264
20262 shiva_wmh       64                     1           rs2413049
20263 shiva_wmh       64                     1           rs4820043
20264 shiva_wmh       64                     1           rs2283881
20265 shiva_wmh       64                     1           rs8139160
20266 shiva_wmh       64                     1           rs5753521
20267 shiva_wmh       64                     1           rs1985531
20268 shiva_wmh       64                     1           rs5749243
20269 shiva_wmh       64                     1           rs737888
20270 shiva_wmh       64                     1           rs7293171
20271 shiva_wmh       64                     1           rs1034588
20272 shiva_wmh       64                     1           rs1985725
20273 shiva_wmh       64                     1           rs9609268
20274 shiva_wmh       64                     1           rs2413033
20275 shiva_wmh       64                     1           rs4820953
20276 shiva_wmh       64                     1           rs4820962
20277 shiva_wmh       64                     1           rs8138596
20278 shiva_wmh       64                     1           rs12152166
20279 shiva_wmh       64                     1           rs2899164
20280 shiva_wmh       64                     1           rs2078803
20281 shiva_wmh       64                     1           rs8139625
20282 shiva_wmh       64                     1           rs9606843
      susierss_pip susierss_pip_rank susierss_locus_gene susierss_locus_start
1     0.0858       1/39              PRKCZ               1067849
2     0.0663       2/39              PRKCZ               1067849
3     0.0624       3/39              PRKCZ               1067849
4     0.0447       4/39              PRKCZ               1067849
5     0.0387       5/39              PRKCZ               1067849
6     0.0341       6/39              PRKCZ               1067849
7     0.0321       7/39              PRKCZ               1067849
8     0.0314       8/39              PRKCZ               1067849
9     0.0301       9/39              PRKCZ               1067849
10    0.0299       10/39             PRKCZ               1067849
11    0.0293       11/39             PRKCZ               1067849
12    0.0280       12/39             PRKCZ               1067849
13    0.0279       13/39             PRKCZ               1067849
14    0.0278       14/39             PRKCZ               1067849
15    0.0260       15/39             PRKCZ               1067849
16    0.0251       16/39             PRKCZ               1067849
17    0.0251       16/39             PRKCZ               1067849
18    0.0238       18/39             PRKCZ               1067849
19    0.0226       19/39             PRKCZ               1067849
20    0.0223       20/39             PRKCZ               1067849
21    0.0222       21/39             PRKCZ               1067849
22    0.0215       22/39             PRKCZ               1067849
23    0.0213       23/39             PRKCZ               1067849
24    0.0210       24/39             PRKCZ               1067849
25    0.0203       25/39             PRKCZ               1067849
26    0.0202       26/39             PRKCZ               1067849
27    0.0202       26/39             PRKCZ               1067849
28    0.0199       28/39             PRKCZ               1067849
29    0.0193       29/39             PRKCZ               1067849
30    0.0193       29/39             PRKCZ               1067849
⋮     ⋮            ⋮                 ⋮                   ⋮
20253 0.0088       60/89             PATZ1               30345081
20254 0.0088       60/89             PATZ1               30345081
20255 0.0087       62/89             PATZ1               30345081
20256 0.0087       62/89             PATZ1               30345081
20257 0.0087       62/89             PATZ1               30345081
20258 0.0086       65/89             PATZ1               30345081
20259 0.0085       66/89             PATZ1               30345081
20260 0.0084       67/89             PATZ1               30345081
20261 0.0083       68/89             PATZ1               30345081
20262 0.0083       68/89             PATZ1               30345081
20263 0.0082       70/89             PATZ1               30345081
20264 0.0080       71/89             PATZ1               30345081
20265 0.0078       72/89             PATZ1               30345081
20266 0.0078       72/89             PATZ1               30345081
20267 0.0072       74/89             PATZ1               30345081
20268 0.0072       74/89             PATZ1               30345081
20269 0.0072       74/89             PATZ1               30345081
20270 0.0071       77/89             PATZ1               30345081
20271 0.0070       78/89             PATZ1               30345081
20272 0.0068       79/89             PATZ1               30345081
20273 0.0068       79/89             PATZ1               30345081
20274 0.0065       81/89             PATZ1               30345081
20275 0.0062       82/89             PATZ1               30345081
20276 0.0059       83/89             PATZ1               30345081
20277 0.0053       84/89             PATZ1               30345081
20278 0.0046       85/89             PATZ1               30345081
20279 0.0045       86/89             PATZ1               30345081
20280 0.0044       87/89             PATZ1               30345081
20281 0.0041       88/89             PATZ1               30345081
20282 0.0039       89/89             PATZ1               30345081
      susierss_locus_end susierss_locus_cytoband ⋯ susierss_SE susierss_P
1     3067849            1p36.33                 ⋯ 0.006052    1.97120e-08
2     3067849            1p36.33                 ⋯ 0.006053    2.63942e-08
3     3067849            1p36.33                 ⋯ 0.006023    2.80590e-08
4     3067849            1p36.33                 ⋯ 0.006090    4.17714e-08
5     3067849            1p36.33                 ⋯ 0.006051    4.78087e-08
6     3067849            1p36.33                 ⋯ 0.006021    5.46071e-08
7     3067849            1p36.33                 ⋯ 0.006080    6.02443e-08
8     3067849            1p36.33                 ⋯ 0.006077    6.17649e-08
9     3067849            1p36.33                 ⋯ 0.006078    6.47913e-08
10    3067849            1p36.33                 ⋯ 0.006077    6.50327e-08
11    3067849            1p36.33                 ⋯ 0.006050    6.67297e-08
12    3067849            1p36.33                 ⋯ 0.006068    7.03248e-08
13    3067849            1p36.33                 ⋯ 0.006082    7.09938e-08
14    3067849            1p36.33                 ⋯ 0.006051    6.92302e-08
15    3067849            1p36.33                 ⋯ 0.006069    7.63485e-08
16    3067849            1p36.33                 ⋯ 0.006070    7.93854e-08
17    3067849            1p36.33                 ⋯ 0.006048    7.97469e-08
18    3067849            1p36.33                 ⋯ 0.006048    8.45387e-08
19    3067849            1p36.33                 ⋯ 0.006045    8.91195e-08
20    3067849            1p36.33                 ⋯ 0.006041    9.08056e-08
21    3067849            1p36.33                 ⋯ 0.006045    9.11429e-08
22    3067849            1p36.33                 ⋯ 0.006063    9.47278e-08
23    3067849            1p36.33                 ⋯ 0.006063    9.59892e-08
24    3067849            1p36.33                 ⋯ 0.006045    9.70585e-08
25    3067849            1p36.33                 ⋯ 0.006063    1.00990e-07
26    3067849            1p36.33                 ⋯ 0.006050    1.01707e-07
27    3067849            1p36.33                 ⋯ 0.006050    1.01583e-07
28    3067849            1p36.33                 ⋯ 0.006044    1.03649e-07
29    3067849            1p36.33                 ⋯ 0.006066    1.07160e-07
30    3067849            1p36.33                 ⋯ 0.006064    1.07163e-07
⋮     ⋮                  ⋮                       ⋱ ⋮           ⋮
20253 32345081           22q12.2                 ⋯ 0.005542    1.54355e-15
20254 32345081           22q12.2                 ⋯ 0.005542    1.55129e-15
20255 32345081           22q12.2                 ⋯ 0.005540    1.58052e-15
20256 32345081           22q12.2                 ⋯ 0.005540    1.58543e-15
20257 32345081           22q12.2                 ⋯ 0.005543    1.53175e-15
20258 32345081           22q12.2                 ⋯ 0.005544    1.56233e-15
20259 32345081           22q12.2                 ⋯ 0.005541    1.60237e-15
20260 32345081           22q12.2                 ⋯ 0.005541    1.59835e-15
20261 32345081           22q12.2                 ⋯ 0.005538    1.61337e-15
20262 32345081           22q12.2                 ⋯ 0.005542    1.65157e-15
20263 32345081           22q12.2                 ⋯ 0.005541    1.68116e-15
20264 32345081           22q12.2                 ⋯ 0.005541    1.71697e-15
20265 32345081           22q12.2                 ⋯ 0.005543    1.73139e-15
20266 32345081           22q12.2                 ⋯ 0.005543    1.77124e-15
20267 32345081           22q12.2                 ⋯ 0.005471    1.87595e-15
20268 32345081           22q12.2                 ⋯ 0.005541    1.91143e-15
20269 32345081           22q12.2                 ⋯ 0.005543    1.89672e-15
20270 32345081           22q12.2                 ⋯ 0.005541    2.00296e-15
20271 32345081           22q12.2                 ⋯ 0.005543    1.94507e-15
20272 32345081           22q12.2                 ⋯ 0.005543    2.00199e-15
20273 32345081           22q12.2                 ⋯ 0.005546    2.08489e-15
20274 32345081           22q12.2                 ⋯ 0.005542    2.08477e-15
20275 32345081           22q12.2                 ⋯ 0.005543    2.22202e-15
20276 32345081           22q12.2                 ⋯ 0.005475    2.10892e-15
20277 32345081           22q12.2                 ⋯ 0.005557    2.79735e-15
20278 32345081           22q12.2                 ⋯ 0.005634    3.41680e-15
20279 32345081           22q12.2                 ⋯ 0.005553    3.29370e-15
20280 32345081           22q12.2                 ⋯ 0.005538    3.30068e-15
20281 32345081           22q12.2                 ⋯ 0.005544    3.56628e-15
20282 32345081           22q12.2                 ⋯ 0.005540    3.78280e-15
      susierss_INFO susierss_is_indep_snp susierss_indep_snp_method
1     0.994385       TRUE                 Both
2     0.995566      FALSE                 NA
3     0.996439      FALSE                 NA
4     0.997427      FALSE                 NA
5     0.996247      FALSE                 NA
6     0.996432      FALSE                 NA
7     0.998924      FALSE                 NA
8     0.997630      FALSE                 NA
9     0.997793      FALSE                 NA
10    0.997686      FALSE                 NA
11    0.999318      FALSE                 NA
12    0.999319      FALSE                 NA
13    0.997637      FALSE                 NA
14    0.996162      FALSE                 NA
15    0.998983      FALSE                 NA
16    0.998894      FALSE                 NA
17    0.999592      FALSE                 NA
18    0.999643      FALSE                 NA
19    0.998995      FALSE                 NA
20    0.999717      FALSE                 NA
21    0.998988      FALSE                 NA
22    0.999154      FALSE                 NA
23    0.999062      FALSE                 NA
24    0.998840      FALSE                 NA
25    0.999113      FALSE                 NA
26    0.999301      FALSE                 NA
27    0.999579      FALSE                 NA
28    1.000000      FALSE                 NA
29    0.998331      FALSE                 NA
30    0.999091      FALSE                 NA
⋮     ⋮             ⋮                     ⋮
20253 0.999828      FALSE                 NA
20254 0.999880      FALSE                 NA
20255 0.999303      FALSE                 NA
20256 0.999829      FALSE                 NA
20257 0.999532      FALSE                 NA
20258 0.999930      FALSE                 NA
20259 0.999928      FALSE                 NA
20260 0.999419      FALSE                 NA
20261 0.999477      FALSE                 NA
20262 0.999810      FALSE                 NA
20263 0.999959      FALSE                 NA
20264 0.999937      FALSE                 NA
20265 0.999711      FALSE                 NA
20266 1.000000      FALSE                 NA
20267 0.996471      FALSE                 NA
20268 0.999811      FALSE                 NA
20269 0.999676      FALSE                 NA
20270 0.999483      FALSE                 NA
20271 0.999643      FALSE                 NA
20272 0.999544      FALSE                 NA
20273 0.999074      FALSE                 NA
20274 0.999459      FALSE                 NA
20275 0.999682      FALSE                 NA
20276 0.997402      FALSE                 NA
20277 0.998496      FALSE                 NA
20278 0.998935      FALSE                 NA
20279 0.998792      FALSE                 NA
20280 1.000000      FALSE                 NA
20281 0.998850      FALSE                 NA
20282 0.998248      FALSE                 NA
      susierss_snp_gene susierss_snp_func susierss_NOVEL susierss_b2_replicated
1     PRKCZ             intronic          Yes            No
2     NA                NA
3     NA                NA
4     NA                NA
5     NA                NA
6     NA                NA
7     NA                NA
8     NA                NA
9     NA                NA
10    NA                NA
11    NA                NA
12    NA                NA
13    NA                NA
14    NA                NA
15    NA                NA
16    NA                NA
17    NA                NA
18    NA                NA
19    NA                NA
20    NA                NA
21    NA                NA
22    NA                NA
23    NA                NA
24    NA                NA
25    NA                NA
26    NA                NA
27    NA                NA
28    NA                NA
29    NA                NA
30    NA                NA
⋮     ⋮                 ⋮                 ⋮              ⋮
20253 NA                NA
20254 NA                NA
20255 NA                NA
20256 NA                NA
20257 NA                NA
20258 NA                NA
20259 NA                NA
20260 NA                NA
20261 NA                NA
20262 NA                NA
20263 NA                NA
20264 NA                NA
20265 NA                NA
20266 NA                NA
20267 NA                NA
20268 NA                NA
20269 NA                NA
20270 NA                NA
20271 NA                NA
20272 NA                NA
20273 NA                NA
20274 NA                NA
20275 NA                NA
20276 NA                NA
20277 NA                NA
20278 NA                NA
20279 NA                NA
20280 NA                NA
20281 NA                NA
20282 NA                NA
      susierss_b2_replicated_bonf
1     No
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮     ⋮
20253
20254
20255
20256
20257
20258
20259
20260
20261
20262
20263
20264
20265
20266
20267
20268
20269
20270
20271
20272
20273
20274
20275
20276
20277
20278
20279
20280
20281
20282

> Format output

Susie rss values are merged into a single column (multiple rows for some rsID)

In [ ]:
library(data.table)

# ── Fixed columns (metadata) ──────────────────────────────────────────────────
meta_cols <- c("CHR", "POS", "REF", "ALT", "dist", "gene", "strand", "ref_matched")

# ── Cell type columns ─────────────────────────────────────────────────────────
cell_cols <- setdiff(colnames(all_res_qced), meta_cols)

# ── Melt to long format ───────────────────────────────────────────────────────
df_long <- melt(all_res_qced,
                id.vars       = meta_cols,
                variable.name = "cell_type",
                value.name    = "delta_prob")

# ── Join rsID ─────────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  rsid_table[, .(rsid, chr, pos, ea, nea)],
  by.x  = c("CHR", "POS", "ALT", "REF"),
  by.y  = c("chr", "pos", "ea",  "nea"),
  all.x = TRUE
)

n_total   <- nrow(df_long)
n_matched <- df_long[!is.na(rsid), .N]
cat("Variants with rsID   :", n_matched, "\n")
cat("Variants without rsID:", n_total - n_matched, "\n")

# ── Join ontology ─────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  ontology[, .(sample_ontology_ID,
               sample_ontology_term,
               sample_ontology_type)],
  by.x  = "cell_type",
  by.y  = "sample_ontology_ID",
  all.x = TRUE
)

# ── Join CAGE info ────────────────────────────────────────────────────────────
df_long <- merge(
  df_long,
  cage_info[, .(clusterID,
                clusterName,
                type,
                geneNameStr,
                geneClassStr)],
  by.x  = "gene",
  by.y  = "clusterID",
  all.x = TRUE
)

# ── Prepare SuSiE RSS CS table ────────────────────────────────────────────────
# Convert to data.table (read.xlsx returns a data.frame)
setDT(cs_table)

# Step 1: Build a human-readable summary string per row
cs_table[, trait_summary := paste0(
  susierss_trait,
  " (locus: ", susierss_risk_loci_num, " / ", susierss_locus_gene,
  ", CS: ",    susierss_cs,
  ", PIP = ",  round(susierss_pip, 3),
  ", rank = ", susierss_pip_rank, ")"
)]

# Step 2: Collapse multiple rows per rsID → one row with "|"-separated string
cs_collapsed <- cs_table[, .(
  trait = paste(trait_summary, collapse = " | ")
), by = rsID]

cat("Unique rsIDs in SuSiE CS table:", nrow(cs_collapsed), "\n")

# ── Join SuSiE RSS CS table by rsid (1-to-1, no cartesian risk) ──────────────
df_long <- merge(
  df_long,
  cs_collapsed,          # rsID + trait (collapsed summary string)
  by.x  = "rsid",
  by.y  = "rsID",
  all.x = TRUE           # keep all df_long rows
)

# Check match rate
n_in_cs <- df_long[!is.na(trait), .N]
cat("Variants matched to SuSiE CS table:", n_in_cs, "\n")
cat("Variants unmatched                :", df_long[is.na(trait), .N], "\n")

# ── Reorder columns ───────────────────────────────────────────────────────────
col_order <- c("gene", "clusterName", "type", "geneNameStr", "geneClassStr",
               "cell_type", "sample_ontology_term", "sample_ontology_type",
               "rsid", "CHR", "POS", "REF", "ALT", "dist", "strand",
               "delta_prob",
               "trait")   # ← single collapsed SuSiE column

df_long <- df_long[, ..col_order]

# Preview
head(df_long)
cat("\nFinal columns:\n")
print(colnames(df_long))

# ── Filter effects ────────────────────────────────────────────────────────────
robust <- df_long[abs(delta_prob) >= 0.1]
cat("Robust effects     (|Δprob| >= 0.1) :", nrow(robust), "\n")

permissive <- df_long[abs(delta_prob) >= 0.05]
cat("Permissive effects (|Δprob| >= 0.05):", nrow(permissive), "\n")

Variants with rsID   : 75293628
Variants without rsID: 0
Unique rsIDs in SuSiE CS table: 10396
Variants matched to SuSiE CS table: 61618272
Variants unmatched                : 13675356

  gene                 clusterName          type     geneNameStr
1 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
2 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
3 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
4 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
5 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
6 chr4:4854782-4854915 e1@ADDG04004854782.E enhancer ADDG04004854782.E
  geneClassStr   cell_type  sample_ontology_term      sample_ontology_type
1 enhancer_locus CL:0000034 stem cell                 cell_type
2 enhancer_locus CL:0000037 hematopoietic stem cell   cell_type
3 enhancer_locus CL:0000047 neuronal stem cell        cell_type
4 enhancer_locus CL:0000049 common myeloid progenitor cell_type
5 enhancer_locus CL:0000056 myoblast                  cell_type
6 enhancer_locus CL:0000057 fibroblast                cell_type
  rsid       CHR  POS     REF ALT dist strand delta_prob
1 rs10000804 chr4 4864299 G   A   9467 N      0
2 rs10000804 chr4 4864299 G   A   9467 N      0
3 rs10000804 chr4 4864299 G   A   9467 N      0
4 rs10000804 chr4 4864299 G   A   9467 N      0
5 rs10000804 chr4 4864299 G   A   9467 N      0
6 rs10000804 chr4 4864299 G   A   9467 N      0
  trait
1 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)
2 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)
3 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)
4 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)
5 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)
6 shiva_deep_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 3, PIP = 0.1, rank = 4/12) | shiva_pvs (locus: 16 / STX18-AS1/MSX1,LOC101928306, CS: 2, PIP = 0.054, rank = 8/54)

Final columns:
 [1] "gene"                 "clusterName"          "type"
 [4] "geneNameStr"          "geneClassStr"         "cell_type"
 [7] "sample_ontology_term" "sample_ontology_type" "rsid"
[10] "CHR"                  "POS"                  "REF"
[13] "ALT"                  "dist"                 "strand"
[16] "delta_prob"           "trait"
Robust effects     (|Δprob| >= 0.1) : 826
Permissive effects (|Δprob| >= 0.05): 16646

In [ ]:
# Write
write.xlsx(permissive, 
           "/network/iss/debette/users/bastien.rioux/mentr/output_formatted/mentr_permissive.xlsx")

In [ ]:
robust

    gene                      clusterName             type
1   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
2   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
3   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
4   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
5   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
6   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
7   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
8   chr8:49426952-49427328    e1@ADDG08049426952.E    enhancer
9   chr8:49427546-49427722    e1@ADDG08049427546.E    enhancer
10  chr2:188326523-188326725  e1@ADDG02188326523.E    enhancer
11  chr2:188326523-188326725  e1@ADDG02188326523.E    enhancer
12  chr2:188326523-188326725  e1@ADDG02188326523.E    enhancer
13  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
14  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
15  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
16  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
17  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
18  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
19  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
20  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
21  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
22  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
23  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
24  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
25  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
26  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
27  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
28  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
29  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
30  chr2:239552819-239552999  e1@ADDG02239552819.E    enhancer
⋮   ⋮                         ⋮                       ⋮
797 chr6:30651242-30651620    e1@ADDG06030651242.E    enhancer
798 chr6:30651242-30651620    e1@ADDG06030651242.E    enhancer
799 chr6:30651242-30651620    e1@ADDG06030651242.E    enhancer
800 chr6:30652314..30652323,- p12@PPP1R18             promoter
801 chr6:30652353..30652362,- p17@PPP1R18             promoter
802 chr6:30652353..30652362,- p17@PPP1R18             promoter
803 chr6:30652445..30652456,- p1@ADDG06030652445.R    promoter
804 chr6:30652445..30652456,- p1@ADDG06030652445.R    promoter
805 chr6:30652466..30652492,- p1@ADDG06030652466.R    promoter
806 chr6:30652497..30652508,- p1@ADDG06030652497.R    promoter
807 chr6:30652686..30652705,+ p1@ADDG06030652686.F    promoter
808 chr6:30652686..30652705,+ p1@ADDG06030652686.F    promoter
809 chr6:31239055..31239088,- p1@ADDG06031239055.R    promoter
810 chr6:31239434..31239487,- p3@HLA-C                promoter
811 chr6:31237739..31237758,+ p5@XXbac-BPG248L24.12   promoter
812 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
813 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
814 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
815 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
816 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
817 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
818 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
819 chr6:31238972..31238985,- p1@ADDG06031238972.R    promoter
820 chr6:31239055..31239088,- p1@ADDG06031239055.R    promoter
821 chr6:31239055..31239088,- p1@ADDG06031239055.R    promoter
822 chr6:31239114..31239134,- p1@ADDG06031239114.R    promoter
823 chr6:31239434..31239487,- p3@HLA-C                promoter
824 chr6:31239434..31239487,- p3@HLA-C                promoter
825 chr6:31240851-31241006    e1@ADDG06031240851.E    enhancer
826 chr6:32549685..32549701,- p9@HLA-DRB1,p9@HLA-DRB5 promoter
    geneNameStr        geneClassStr   cell_type
1   ADDG08049426952.E  enhancer_locus CL:0000084
2   ADDG08049426952.E  enhancer_locus CL:0000542
3   ADDG08049426952.E  enhancer_locus CL:0000576
4   ADDG08049426952.E  enhancer_locus CL:0000798
5   ADDG08049426952.E  enhancer_locus CL:0000842
6   ADDG08049426952.E  enhancer_locus CL:0000860
7   ADDG08049426952.E  enhancer_locus CL:0002582
8   ADDG08049426952.E  enhancer_locus LCL154
9   ADDG08049427546.E  enhancer_locus UBERON:0001829
10  ADDG02188326523.E  enhancer_locus UBERON:0000473
11  ADDG02188326523.E  enhancer_locus UBERON:0000991
12  ADDG02188326523.E  enhancer_locus UBERON:0002323
13  ADDG02239552819.E  enhancer_locus CL:0000037
14  ADDG02239552819.E  enhancer_locus CL:0000094
15  ADDG02239552819.E  enhancer_locus CL:0000236
16  ADDG02239552819.E  enhancer_locus CL:0000451
17  ADDG02239552819.E  enhancer_locus CL:0000569
18  ADDG02239552819.E  enhancer_locus CL:0000767
19  ADDG02239552819.E  enhancer_locus CL:0000771
20  ADDG02239552819.E  enhancer_locus CL:0000775
21  ADDG02239552819.E  enhancer_locus CL:0000784
22  ADDG02239552819.E  enhancer_locus CL:0000837
23  ADDG02239552819.E  enhancer_locus CL:0000840
24  ADDG02239552819.E  enhancer_locus CL:0000842
25  ADDG02239552819.E  enhancer_locus CL:0002077
26  ADDG02239552819.E  enhancer_locus CL:0002396
27  ADDG02239552819.E  enhancer_locus CL:0002397
28  ADDG02239552819.E  enhancer_locus CL:0002582
29  ADDG02239552819.E  enhancer_locus CL:0002619
30  ADDG02239552819.E  enhancer_locus UBERON:0000178
⋮   ⋮                  ⋮              ⋮
797 ADDG06030651242.E  enhancer_locus UBERON:0002242
798 ADDG06030651242.E  enhancer_locus UBERON:0003350
799 ADDG06030651242.E  enhancer_locus UBERON:0003729
800 PPP1R18            coding_mRNA    UBERON:0003498
801 PPP1R18            coding_mRNA    CL:0000362
802 PPP1R18            coding_mRNA    CL:0000569
803 ADDG06030652445.R  promoter_locus CL:0002556
804 ADDG06030652445.R  promoter_locus UBERON:0002185
805 ADDG06030652466.R  promoter_locus CL:0002368
806 ADDG06030652497.R  promoter_locus CL:0000362
807 ADDG06030652686.F  promoter_locus CL:0000312
808 ADDG06030652686.F  promoter_locus CL:0002368
809 ADDG06031239055.R  promoter_locus CL:0000082
810 HLA-C              coding_mRNA    CL:0002567
811 XXbac-BPG248L24.12 pseudogene     CL:0002582
812 ADDG06031238972.R  promoter_locus CL:0002552
813 ADDG06031238972.R  promoter_locus CL:0002561
814 ADDG06031238972.R  promoter_locus CL:0002580
815 ADDG06031238972.R  promoter_locus CL:0002592
816 ADDG06031238972.R  promoter_locus CL:0002593
817 ADDG06031238972.R  promoter_locus CL:0002615
818 ADDG06031238972.R  promoter_locus CL:0002617
819 ADDG06031238972.R  promoter_locus UBERON:0002242
820 ADDG06031239055.R  promoter_locus CL:0002521
821 ADDG06031239055.R  promoter_locus CL:0002571
822 ADDG06031239114.R  promoter_locus CL:1000413
823 HLA-C              coding_mRNA    CL:0000148
824 HLA-C              coding_mRNA    CL:0002567
825 ADDG06031240851.E  enhancer_locus CL:0000134
826 HLA-DRB1;HLA-DRB5  coding_mRNA    CL:0000221
    sample_ontology_term                               sample_ontology_type
1   T cell                                             cell_type
2   lymphocyte                                         cell_type
3   monocyte                                           cell_type
4   gamma-delta T cell                                 cell_type
5   mononuclear cell                                   cell_type
6   classical monocyte                                 cell_type
7   visceral preadipocyte                              cell_type
8   NA                                                 NA
9   major salivary gland                               tissue
10  testis                                             tissue
11  gonad                                              tissue
12  coelemic cavity lumen                              tissue
13  hematopoietic stem cell                            cell_type
14  granulocyte                                        cell_type
15  B cell                                             cell_type
16  dendritic cell                                     cell_type
17  cardiac mesenchymal cell                           cell_type
18  basophil                                           cell_type
19  eosinophil                                         cell_type
20  neutrophil                                         cell_type
21  plasmacytoid dendritic cell                        cell_type
22  hematopoietic multipotent progenitor cell          cell_type
23  immature conventional dendritic cell               cell_type
24  mononuclear cell                                   cell_type
25  ecto-epithelial cell                               cell_type
26  CD14-low, CD16-positive monocyte                   cell_type
27  CD14-positive, CD16-positive monocyte              cell_type
28  visceral preadipocyte                              cell_type
29  adult endothelial progenitor cell                  cell_type
30  blood                                              tissue
⋮   ⋮                                                  ⋮
797 nucleus pulposus                                   tissue
798 epithelium of mucosa                               tissue
799 mouth mucosa                                       tissue
800 heart blood vessel                                 tissue
801 epidermal cell                                     cell_type
802 cardiac mesenchymal cell                           cell_type
803 fibroblast of periodontium                         cell_type
804 bronchus                                           tissue
805 respiratory epithelial cell                        cell_type
806 epidermal cell                                     cell_type
807 keratinocyte                                       cell_type
808 respiratory epithelial cell                        cell_type
809 epithelial cell of lung                            cell_type
810 light melanocyte                                   cell_type
811 visceral preadipocyte                              cell_type
812 fibroblast of gingiva                              cell_type
813 outer root sheath cell                             cell_type
814 preadipocyte of the breast                         cell_type
815 smooth muscle cell of the coronary artery          cell_type
816 smooth muscle cell of the internal thoracic artery cell_type
817 adipocyte of omentum tissue                        cell_type
818 adipocyte of breast                                cell_type
819 nucleus pulposus                                   tissue
820 subcutaneous fat cell                              cell_type
821 hepatic mesenchymal stem cell                      cell_type
822 endothelial cell of artery                         cell_type
823 melanocyte                                         cell_type
824 light melanocyte                                   cell_type
825 mesenchymal stem cell                              cell_type
826 ectodermal cell                                    cell_type
    rsid       CHR  POS       REF ALT dist  strand delta_prob
1   rs10092171 chr8  49427167 G   A     -5  N      -0.1045710
2   rs10092171 chr8  49427167 G   A     -5  N      -0.1055892
3   rs10092171 chr8  49427167 G   A     -5  N      -0.1135946
4   rs10092171 chr8  49427167 G   A     -5  N      -0.1108362
5   rs10092171 chr8  49427167 G   A     -5  N      -0.2121058
6   rs10092171 chr8  49427167 G   A     -5  N      -0.1057864
7   rs10092171 chr8  49427167 G   A     -5  N      -0.1217962
8   rs10092171 chr8  49427167 G   A     -5  N      -0.1072644
9   rs10092171 chr8  49427167 G   A   -466  N      -0.1135367
10  rs10201618 chr2 188326949 C   A    370  N      -0.1333658
11  rs10201618 chr2 188326949 C   A    370  N      -0.1081975
12  rs10201618 chr2 188326949 C   A    370  N      -0.1323136
13  rs10203711 chr2 239553368 C   T    458  N      -0.1946692
14  rs10203711 chr2 239553368 C   T    458  N      -0.1797364
15  rs10203711 chr2 239553368 C   T    458  N      -0.1046413
16  rs10203711 chr2 239553368 C   T    458  N      -0.1460577
17  rs10203711 chr2 239553368 C   T    458  N      -0.1086136
18  rs10203711 chr2 239553368 C   T    458  N      -0.1381755
19  rs10203711 chr2 239553368 C   T    458  N      -0.1584516
20  rs10203711 chr2 239553368 C   T    458  N      -0.1860349
21  rs10203711 chr2 239553368 C   T    458  N      -0.2475610
22  rs10203711 chr2 239553368 C   T    458  N      -0.1918367
23  rs10203711 chr2 239553368 C   T    458  N      -0.1714940
24  rs10203711 chr2 239553368 C   T    458  N      -0.2038528
25  rs10203711 chr2 239553368 C   T    458  N      -0.1022275
26  rs10203711 chr2 239553368 C   T    458  N      -0.1888088
27  rs10203711 chr2 239553368 C   T    458  N      -0.1118617
28  rs10203711 chr2 239553368 C   T    458  N      -0.1071656
29  rs10203711 chr2 239553368 C   T    458  N      -0.1472683
30  rs10203711 chr2 239553368 C   T    458  N      -0.1800040
⋮   ⋮          ⋮    ⋮         ⋮   ⋮   ⋮     ⋮      ⋮
797 rs9262142  chr6 30650026  G   A   -1331 N      -0.1194979
798 rs9262142  chr6 30650026  G   A   -1331 N      -0.1097242
799 rs9262142  chr6 30650026  G   A   -1331 N      -0.1009990
800 rs9262142  chr6 30650026  G   A   -2293 -      -0.1122297
801 rs9262142  chr6 30650026  G   A   -2332 -      -0.1016484
802 rs9262142  chr6 30650026  G   A   -2332 -      -0.1072960
803 rs9262142  chr6 30650026  G   A   -2425 -      -0.1073321
804 rs9262142  chr6 30650026  G   A   -2425 -      -0.1053876
805 rs9262142  chr6 30650026  G   A   -2456 -      -0.1132845
806 rs9262142  chr6 30650026  G   A   -2477 -      -0.1048632
807 rs9262142  chr6 30650026  G   A   -2673 +      -0.1285594
808 rs9262142  chr6 30650026  G   A   -2673 +      -0.1132845
809 rs9264663  chr6 31239205  C   T     123 -      -0.1026807
810 rs9264663  chr6 31239205  C   T    -273 -      -0.1022188
811 rs9264664  chr6 31239227  C   T    1474 +      -0.1071656
812 rs9264664  chr6 31239227  C   T     248 -      -0.1145661
813 rs9264664  chr6 31239227  C   T     248 -      -0.1225850
814 rs9264664  chr6 31239227  C   T     248 -      -0.1355891
815 rs9264664  chr6 31239227  C   T     248 -      -0.1087711
816 rs9264664  chr6 31239227  C   T     248 -      -0.1096220
817 rs9264664  chr6 31239227  C   T     248 -      -0.1086562
818 rs9264664  chr6 31239227  C   T     248 -      -0.1101525
819 rs9264664  chr6 31239227  C   T     248 -      -0.1194979
820 rs9264664  chr6 31239227  C   T     145 -      -0.1178820
821 rs9264664  chr6 31239227  C   T     145 -      -0.1027745
822 rs9264664  chr6 31239227  C   T     105 -      -0.1040158
823 rs9264664  chr6 31239227  C   T    -251 -      -0.1025641
824 rs9264664  chr6 31239227  C   T    -251 -      -0.1022188
825 rs9264664  chr6 31239227  C   T   -1715 N      -0.1098822
826 rs9269822  chr6 32549810  G   A     114 -       0.1395840
    trait
1   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
2   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
3   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
4   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
5   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
6   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
7   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
8   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
9   shiva_wmh (locus: 30 / UBE2V2,LOC101929268, CS: 1, PIP = 0.035, rank = 3/76)
10  bianca_deep_wmh (locus: 8 / CALCRL, CS: 1, PIP = 0.003, rank = 39/113) | shiva_deep_pvs (locus: 10 / CALCRL, CS: 1, PIP = 0.006, rank = 121/164) | shiva_pvs (locus: 9 / ZSWIM2,CALCRL, CS: 1, PIP = 0.004, rank = 146/168)
11  bianca_deep_wmh (locus: 8 / CALCRL, CS: 1, PIP = 0.003, rank = 39/113) | shiva_deep_pvs (locus: 10 / CALCRL, CS: 1, PIP = 0.006, rank = 121/164) | shiva_pvs (locus: 9 / ZSWIM2,CALCRL, CS: 1, PIP = 0.004, rank = 146/168)
12  bianca_deep_wmh (locus: 8 / CALCRL, CS: 1, PIP = 0.003, rank = 39/113) | shiva_deep_pvs (locus: 10 / CALCRL, CS: 1, PIP = 0.006, rank = 121/164) | shiva_pvs (locus: 9 / ZSWIM2,CALCRL, CS: 1, PIP = 0.004, rank = 146/168)
13  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
14  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
15  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
16  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
17  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
18  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
19  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
20  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
21  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
22  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
23  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
24  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
25  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
26  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
27  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
28  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
29  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
30  shiva_deep_pvs (locus: 11 / LINC01107,LOC100287387, CS: 1, PIP = 0.007, rank = 66/67)
⋮   ⋮
797 NA
798 NA
799 NA
800 NA
801 NA
802 NA
803 NA
804 NA
805 NA
806 NA
807 NA
808 NA
809 NA
810 NA
811 NA
812 NA
813 NA
814 NA
815 NA
816 NA
817 NA
818 NA
819 NA
820 NA
821 NA
822 NA
823 NA
824 NA
825 NA
826 NA